// Generated by https://quicktype.io

export interface BookmarkFolderModel {
    id: string;
    name: string;
    bgColor: string;
    bookmarks: BookmarkModel[];
}

export interface BookmarkModel {
    id: string;
    name: string;
    url: string;
    bgColor: string;
}
